project:
  type: website
  output-dir: empl-web

website:
  title: "Job Market Analysis 2024"
  navbar:
    pinned: true
    background: "#ffffffcc"
    foreground: "#1F2937"
    logo: assets/logo.svg
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Research"
      - href: data_analysis.qmd
        text: "Data Analysis"
      - href: career_plan.qmd
        text: "Career Strategy"
      - href: about.qmd
        text: "About Us"

format:
  html:
    theme:
      light: flatly
      dark: quartz
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    page-layout: full
    smooth-scroll: true
    code-fold: true

include-after-body:
  - footer.html