project:
  type: website
  output-dir: empl-web

website:
  title: "Job Market Analysis 2024"
  search: true
  navbar:
    pinned: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Introduction"
        href: introduction.qmd
      - text: "Research Background"
        href: research_background.qmd
      - text: "Analysis"
        menu:
          - text: "Overview & Pipeline"
            href: data_analysis.qmd
          - text: "Data Cleaning & Preprocessing"
            href: data_cleaning.qmd
          - text: "Exploratory Data Analysis"
            href: eda.qmd
          - text: "Skill Gap Analysis"
            href: skill_gap_analysis.qmd
          - text: "ML Methods"
            href: ml_methods.qmd
          - text: "NLP Methods"
            href: nlp_methods.qmd
      - text: "Career Strategy"
        href: career_plan.qmd
      - text: "About Us"
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: quartz
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    smooth-scroll: true
    page-layout: full

include-after-body:
  - footer.html