project:
  type: website
  output-dir: docs

website:
  title: "Gender Disparities in Labor Force Analysis (2024)"
  search: true
  navbar:
    pinned: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research Background"
        href: research_background.qmd
      - text: "Analysis"
        menu:
          - text: "Gender Disparities Overview"
            href: fred_api_analysis.qmd
          - text: "Data Cleaning & Preprocessing"
            href: data_cleaning.qmd
          - text: "Exploratory Data Analysis"
            href: eda.qmd
          - text: "Gender Dominance in Job Postings"
            href: gender_dom_analysis.qmd
          - text: "Machine-Learning Models"
            href: ml_methods.qmd
          - text: "NLP Analysis"
            href: nlp_methods.qmd
          - text: "Skill Gap Analysis"
            href: skill_gap_analysis.qmd
      - text: "Career Strategy"
        href: career_plan.qmd
      - text: "About Us"
        href: about.qmd

format:
  html:
    theme:
      light: flatly
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: false
    smooth-scroll: true
    page-layout: full

include-after-body:
  - footer.html