project:
  type: website
  output-dir: empl-web

website:
  title: "Job Market Analysis 2024"
  search: true
  navbar:
    pinned: true
    right:
      - text: "Home"
        href: index.qmd
      - text: "Research Introduction"
        href: research_introduction.qmd
      - text: "Data Analysis"
        href: data_analysis.qmd
      - text: "Career Strategy"
        href: career_plan.qmd
      - text: "About Us"
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: quartz
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: false
    smooth-scroll: true
    page-layout: full

include-after-body:
  - footer.html

